### ISSUE TITLE
I am not able to update profile and can not add assignments

### ISSUE THREAD

**Issue by Antoninsticator** [ketanchoyal/Our-E-School#15]
Hello there,

Thanks for the project... I am unable to update profile and add to the database created in firebase. Need more documentation regarding Firebase functions and typescript used. Please let me know.

**Comment by Antoninsticator** [comment]
need to understand more on the product.

**Comment by ketanchoyal** [comment]
You have to publish firebase functions and add your firebase config json to make it work.
