### ISSUE TITLE
Need Documentation

### ISSUE THREAD

**Issue by livingloves** [ketanchoyal/Our-E-School#18]
```
I need the Docomentation of Setting Up The Firebase 
And Need Some Upgrade  on 
```

### Online confarence Meeting  

Please make It Up

**Comment by kzawadi** [comment]
Brother The first Folder of This Project is All about firestore db strusture you need to start This Project...There is nothing else special neeeded .Just conect a flutter App to firestore and do a config as shown in dbstrusture Folder (First folder of this project)   ....But if you can't a flutter App in firestore then  you have to start with that by searching relevant doc adn tutos
