### ISSUE TITLE
Error while compiling in Android Studio

### ISSUE THREAD

**Issue by TurboTronix** [ketanchoyal/Our-E-School#23]
I'm new to flutter, can't figure out why I'm getting this:

```
lib/UI/pages/Profiles/GuardianProfile.dart:82:7: Error: The getter 'ScaffoldMessenger' isn't defined for the class '_GuardianProfilePageState'.
 - '_GuardianProfilePageState' is from 'package:ourESchool/UI/pages/Profiles/GuardianProfile.dart' ('lib/UI/pages/Profiles/GuardianProfile.dart').
Try correcting the name to the name of an existing getter, or defining a getter or field named 'ScaffoldMessenger'.
      ScaffoldMessenger.of(context).showSnackBar(ksnackBar(
      ^^^^^^^^^^^^^^^^^
```
Is it because I did not create a firebase connection to this yet?

**Comment by TurboTronix** [comment]
Also getting this warning not sure if this is even needed...

WARNING: The option setting 'android.enableR8=true' is deprecated.
It will be removed in version 5.0 of the Android Gradle plugin.
You will no longer be able to disable R8

**Comment by TurboTronix** [comment]
OK so now I get the following error: 
`No matching client found for package name 'com.ketanchoyal.our_e_school'`

I believe **com.ketanchoyal.our_e_school** is your firebase but where did you initialize this, what file?

**Comment by ketanchoyal** [comment]
you need to setup your firebase project and deploy the firebase functions.



> OK so now I get the following error:
> `No matching client found for package name 'com.ketanchoyal.our_e_school'`
> 
> I believe **com.ketanchoyal.our_e_school** is your firebase but where did you initialize this, what file?

can you provide some more detail on this?

**Comment by TurboTronix** [comment]
Sorry i gave up on your code, couldn't make it work. I'm working on another flutter code,  it uses mysql. Once i get more into it I'll try to mimic your GUI since i really like it. I'm also integrating rfid login into it. Love how simple flutter is and it all started after seeing your code, did not know of flutter before so thanks for that :)
