### ISSUE TITLE
Login Authentication Error

### ISSUE THREAD

**Issue by zainiftikhar20** [ketanchoyal/Our-E-School#28]
Hye.

when I tried to login the login screen gets stuck and gives an error in terminal. Can you help me out there. I am attaching some screenshots here.
![1](https://user-images.githubusercontent.com/71585418/115988740-8ea8a980-a5d4-11eb-9b83-534033dcfaee.png)
![2](https://user-images.githubusercontent.com/71585418/115988743-90726d00-a5d4-11eb-8843-50454c71a0cd.png)
![3](https://user-images.githubusercontent.com/71585418/115988744-90726d00-a5d4-11eb-819b-808e384e5b64.png)
![4](https://user-images.githubusercontent.com/71585418/115988746-910b0380-a5d4-11eb-908a-edca69db2e22.png)
![5](https://user-images.githubusercontent.com/71585418/115988748-910b0380-a5d4-11eb-89a9-2295e8e2de18.png)
![6](https://user-images.githubusercontent.com/71585418/115988749-91a39a00-a5d4-11eb-9766-44681d028e7b.png)
![7](https://user-images.githubusercontent.com/71585418/115988750-923c3080-a5d4-11eb-84a9-d09e0b86583a.png)
![8](https://user-images.githubusercontent.com/71585418/115988751-923c3080-a5d4-11eb-8426-32eb5a939e00.png)
![9](https://user-images.githubusercontent.com/71585418/115988752-92d4c700-a5d4-11eb-8b34-ce8e428f9e77.png)
![WhatsApp Image 2021-04-25 at 2 40 39 PM](https://user-images.githubusercontent.com/71585418/115988753-936d5d80-a5d4-11eb-9bd8-68a843eb37f6.jpeg)
![WhatsApp Image 2021-04-25 at 2 40 39 PM (1)](https://user-images.githubusercontent.com/71585418/115988754-936d5d80-a5d4-11eb-8f80-5e83bdd6a39e.jpeg)

**Comment by ketanchoyal** [comment]
mistake while creating database childId and parentId are not in list form, they have to be defined as map
