### ISSUE TITLE
bugs

### ISSUE THREAD

**Issue by vikashkjha26** [ketanchoyal/Our-E-School#30]
the project contains a lot of bugs

**Comment by su-khi** [comment]
Dear VikasJha26

Rather than complaining in one line it would help if you make a list of bugs so that the author or someone who has already using this project can comment or fix. At least, that way you could contribute to this open source project.

On 12 May 2021, at 12:39, vikashkjha26 ***@***.***> wrote:

﻿

the project contains a lot of bugs

**Comment by vikashkjha26** [comment]
the errors are

Compile failed

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:5:8:
Error: Error when reading
'../stores/store_12/hot-projects/164964/lib/core/Server.dart': No such file
or directory

import 'package:ourESchool/core/Server.dart';

^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:35:20:
Error: Getter not found: 'Server'.

String baseUrl = Server.baseUrl;

^^^^^^

../stores/store_12/hot-projects/1Compile failed

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:5:8:
Error: Error when reading
'../stores/store_12/hot-projects/164964/lib/core/Server.dart': No such file
or directory

import 'package:ourESchool/core/Server.dart';

^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:35:20:
Error: Getter not found: 'Server'.

String baseUrl = Server.baseUrl;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:37:22:
Error: Getter not found: 'Server'.

String webApiUrl = Server.baseUrl + Server.webApi;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:37:39:
Error: Getter not found: 'Server'.

String webApiUrl = Server.baseUrl + Server.webApi;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Dashboard/Holidays/HolidayPage.dart:39:13:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/Widgets/DynamicThemeChanger.dart:25:20:
Error: The method 'ancestorStateOfType' isn't defined for the class
'BuildContext'.

- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('packages/flutter/lib/src/widgets/framework.dart').

Try correcting the name to the name of an existing method, or defining a
method named 'ancestorStateOfType'.

return context.ancestorStateOfType(const TypeMatcher<DynamicThemeState>());

^^^^^^^^^^^^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Dashboard/Holidays/holiday_details_page.dart:278:7:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Login/LoginPage.dart:73:11:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^
0
------------------------------
[image: image.png]

[image: image.png]

No branch64964/lib/core/services/Services.dart:37:22: Error: Getter not
found: 'Server'.

String webApiUrl = Server.baseUrl + Server.webApi;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:37:39:
Error: Getter not found: 'Server'.

String webApiUrl = Server.baseUrl + Server.webApi;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:40:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.profileUpdate;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:43:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.getProfileData;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:46:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.postAnnouncement;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:7:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:24:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/core/services/Services.dart:49:40:
Error: Getter not found: 'Server'.

Server.baseUrl + Server.webApi + Server.addAssignment;

^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Dashboard/Holidays/HolidayPage.dart:39:13:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/Widgets/DynamicThemeChanger.dart:25:20:
Error: The method 'ancestorStateOfType' isn't defined for the class
'BuildContext'.

- 'BuildContext' is from 'package:flutter/src/widgets/framework.dart'
('packages/flutter/lib/src/widgets/framework.dart').

Try correcting the name to the name of an existing method, or defining a
method named 'ancestorStateOfType'.

return context.ancestorStateOfType(const TypeMatcher<DynamicThemeState>());

^^^^^^^^^^^^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Dashboard/Holidays/holiday_details_page.dart:278:7:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^

../stores/store_12/hot-projects/164964/lib/UI/pages/Login/LoginPage.dart:73:11:
Error: No named parameter with the name 'resizeToAvoidBottomPadding'.

resizeToAvoidBottomPadding: false,

^^^^^^^^^^^^^^^^^^^^^^^^^^

packages/flutter/lib/src/material/scaffold.dart:1451:9: Context: Found this
candidate, but the arguments don't match.

const Scaffold({

^^^^^^^^
0
------------------------------
[image: image.png]

[image: image.png]

No branch

**Comment by ketanchoyal** [comment]
@vikashkjha26 before working on the project please refer to the documentation, it says to create a Server.dart file. Moreover, it is clearly stated that this project will compile successfully only if you're using flutter 1.x.

**Comment by vikashkjha26** [comment]
Download it and try to run it yourself first.

**Comment by ketanchoyal** [comment]
@vikashkjha26 looks like you're pro in flutter, why don't you make a PR which solves these bugs.

**Comment by ketanchoyal** [comment]
@vikashkjha26 please use sponsor button on my profile if you want personalized support

**Comment by vikashkjha26** [comment]
I was wondering why i commented instead of reporting..

**Comment by ketanchoyal** [comment]
@vikashkjha26 what's your problem? it's nobody's fault that you don't know how to debug code or read documentation
